// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_8goNEUqdFOyzpFyaq_3WipFrPh5PfqA',
    appId: '1:573274239402:web:d6c29408990e4e43edfbd3',
    messagingSenderId: '573274239402',
    projectId: 'venky-434',
    authDomain: 'venky-434.firebaseapp.com',
    storageBucket: 'venky-434.firebasestorage.app',
    measurementId: 'G-02V2XTS4XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ8AkfcjUdDb7gJkKbtqYzHhLgNxdV6RI',
    appId: '1:573274239402:android:d30884f39f16f752edfbd3',
    messagingSenderId: '573274239402',
    projectId: 'venky-434',
    storageBucket: 'venky-434.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArDsaSbFiM41x4-8U9GM1Y9BrMeZk_gTA',
    appId: '1:573274239402:ios:b9a95609ca50dd89edfbd3',
    messagingSenderId: '573274239402',
    projectId: 'venky-434',
    storageBucket: 'venky-434.firebasestorage.app',
    iosBundleId: 'com.example.agriMarketplaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArDsaSbFiM41x4-8U9GM1Y9BrMeZk_gTA',
    appId: '1:573274239402:ios:b9a95609ca50dd89edfbd3',
    messagingSenderId: '573274239402',
    projectId: 'venky-434',
    storageBucket: 'venky-434.firebasestorage.app',
    iosBundleId: 'com.example.agriMarketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_8goNEUqdFOyzpFyaq_3WipFrPh5PfqA',
    appId: '1:573274239402:web:dc9138e4805603d5edfbd3',
    messagingSenderId: '573274239402',
    projectId: 'venky-434',
    authDomain: 'venky-434.firebaseapp.com',
    storageBucket: 'venky-434.firebasestorage.app',
    measurementId: 'G-VRN9FVTCZL',
  );
}
